# Generated by Django 5.1.1 on 2024-09-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
